In [18]:
##
import MySQLdb
import pandas as pd
import matplotlib.pylab as plt
import numpy as np

In [12]:
con = MySQLdb.connect("safar.csail.mit.edu","mimic3","3CIMIM_v30","mimic3v14")

In [23]:
df = pd.read_sql('SELECT * FROM microbiologyevents LIMIT 100', con = con)

In [24]:
df

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTDATE,CHARTTIME,SPEC_ITEMID,SPEC_TYPE_DESC,ORG_ITEMID,ORG_NAME,ISOLATE_NUM,AB_ITEMID,AB_NAME,DILUTION_TEXT,DILUTION_COMPARISON,DILUTION_VALUE,INTERPRETATION
0,1,2,163353,2138-07-17,2138-07-17 22:10:00,70014,BLOOD CULTURE - NEONATE,NaN,None,NaN,NaN,None,None,None,NaN,None
1,2,3,145834,2101-10-20,2101-10-20 13:00:00,70070,SWAB,80223.0,PROBABLE ENTEROCOCCUS,1.0,NaN,None,None,None,NaN,None
2,3,3,145834,2101-10-20,2101-10-20 13:00:00,70070,SWAB,80075.0,YEAST,1.0,NaN,None,None,None,NaN,None
3,4,3,145834,2101-10-20,2101-10-20 13:00:00,70070,SWAB,80155.0,"STAPHYLOCOCCUS, COAGULASE NEGATIVE",1.0,NaN,None,None,None,NaN,None
4,5,3,145834,2101-10-20,2101-10-20 13:00:00,70070,SWAB,80058.0,GRAM NEGATIVE ROD(S),1.0,NaN,None,None,None,NaN,None
5,6,3,145834,2101-10-20,2101-10-20 18:00:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
6,7,3,145834,2101-10-20,2101-10-20 18:30:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
7,8,3,145834,2101-10-20,NaT,70079,URINE,80075.0,YEAST,1.0,NaN,None,None,None,NaN,None
8,9,3,145834,2101-10-21,2101-10-21 04:00:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
9,10,3,145834,2101-10-21,2101-10-21 04:00:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
10,11,3,145834,2101-10-21,2101-10-21 04:15:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
11,12,3,145834,2101-10-21,2101-10-21 04:30:00,70079,URINE,80075.0,YEAST,1.0,NaN,None,None,None,NaN,None
12,13,3,145834,2101-10-21,2101-10-21 04:30:00,70062,SPUTUM,80075.0,YEAST,1.0,NaN,None,None,None,NaN,None
13,14,3,145834,2101-10-21,2101-10-21 12:48:00,70023,CATHETER TIP-IV,NaN,None,NaN,NaN,None,None,None,NaN,None
14,15,3,145834,2101-10-21,2101-10-21 20:00:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
15,16,3,145834,2101-10-21,2101-10-21 20:00:00,70011,BLOOD CULTURE ( MYCO/F LYTIC BOTTLE),NaN,None,NaN,NaN,None,None,None,NaN,None
16,17,3,145834,2101-10-26,NaT,70079,URINE,NaN,None,NaN,NaN,None,None,None,NaN,None
17,18,3,145834,2101-10-28,2101-10-28 11:00:00,70064,STOOL,NaN,None,NaN,NaN,None,None,None,NaN,None
18,19,4,185777,2191-03-16,2191-03-16 05:00:00,70079,URINE,NaN,None,NaN,NaN,None,None,None,NaN,None
19,20,4,185777,2191-03-16,2191-03-16 05:00:00,70081,URINE,NaN,None,NaN,NaN,None,None,None,NaN,None
20,21,4,185777,2191-03-16,2191-03-16 12:30:00,70062,SPUTUM,80260.0,POSITIVE FOR PNEUMOCYSTIS CARINII,1.0,NaN,None,None,None,NaN,None
21,22,4,185777,2191-03-16,NaT,70012,BLOOD CULTURE,80023.0,STAPH AUREUS COAG +,1.0,NaN,None,None,None,NaN,None
22,23,4,185777,2191-03-16,NaT,70012,BLOOD CULTURE,80023.0,STAPH AUREUS COAG +,2.0,NaN,None,None,None,NaN,None
23,24,4,185777,2191-03-17,2191-03-17 05:00:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
24,25,4,185777,2191-03-17,2191-03-17 12:00:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
25,26,4,185777,2191-03-17,NaT,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
26,27,4,185777,2191-03-18,2191-03-18 08:00:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
27,28,4,185777,2191-03-18,2191-03-18 08:15:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
28,29,4,185777,2191-03-18,2191-03-18 11:15:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
29,30,4,185777,2191-03-18,2191-03-18 12:40:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,21,109451,2134-09-12,2134-09-12 01:08:00,70079,URINE,NaN,None,NaN,NaN,None,None,None,NaN,None
71,72,21,109451,2134-09-19,2134-09-19 10:36:00,70079,URINE,80060.0,CANDIDA ALBICANS,1.0,NaN,None,None,None,NaN,None
72,73,21,109451,2134-09-19,2134-09-19 15:55:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
73,74,21,109451,2134-09-19,2134-09-19 16:20:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
74,75,21,109451,2134-09-20,2134-09-20 21:51:00,70079,URINE,80254.0,"CANDIDA ALBICANS, PRESUMPTIVE IDENTIFICATION",1.0,NaN,None,None,None,NaN,None
75,76,21,111970,2135-01-30,2135-01-30 19:00:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
76,77,21,111970,2135-01-30,2135-01-30 19:05:00,70012,BLOOD CULTURE,80168.0,ENTEROCOCCUS FAECIUM,2.0,90009.0,CHLORAMPHENICOL,<=4,<=,4.0,S
77,78,21,111970,2135-01-30,2135-01-30 19:05:00,70012,BLOOD CULTURE,80168.0,ENTEROCOCCUS FAECIUM,2.0,90002.0,PENICILLIN,=>64,=>,64.0,R
78,79,21,111970,2135-01-30,2135-01-30 19:05:00,70012,BLOOD CULTURE,80168.0,ENTEROCOCCUS FAECIUM,2.0,90015.0,VANCOMYCIN,=>32,=>,32.0,R
79,80,21,111970,2135-01-30,2135-01-30 19:05:00,70012,BLOOD CULTURE,80168.0,ENTEROCOCCUS FAECIUM,2.0,90025.0,LEVOFLOXACIN,=>8,=>,8.0,R
80,81,21,111970,2135-01-30,2135-01-30 19:05:00,70012,BLOOD CULTURE,80168.0,ENTEROCOCCUS FAECIUM,1.0,NaN,None,None,None,NaN,None
81,82,21,111970,2135-01-30,2135-01-30 19:05:00,70012,BLOOD CULTURE,80168.0,ENTEROCOCCUS FAECIUM,2.0,90004.0,AMPICILLIN,=>32,=>,32.0,R
82,83,21,111970,2135-01-30,2135-01-30 19:05:00,70012,BLOOD CULTURE,80168.0,ENTEROCOCCUS FAECIUM,2.0,90031.0,LINEZOLID,2,=,2.0,S
83,84,21,111970,2135-01-31,2135-01-31 00:29:00,70023,CATHETER TIP-IV,NaN,None,NaN,NaN,None,None,None,NaN,None
84,85,21,111970,2135-01-31,2135-01-31 03:35:00,70081,URINE,NaN,None,NaN,NaN,None,None,None,NaN,None
85,86,21,111970,2135-01-31,2135-01-31 03:35:00,70079,URINE,NaN,None,NaN,NaN,None,None,None,NaN,None
86,87,21,111970,2135-01-31,2135-01-31 09:20:00,70064,STOOL,80139.0,CLOSTRIDIUM DIFFICILE,1.0,NaN,None,None,None,NaN,None
87,88,21,111970,2135-02-01,2135-02-01 12:06:00,70064,STOOL,NaN,None,NaN,NaN,None,None,None,NaN,None
88,89,21,111970,2135-02-01,2135-02-01 12:06:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
89,90,21,111970,2135-02-01,2135-02-01 12:06:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
90,91,21,111970,2135-02-01,2135-02-01 12:06:00,70011,BLOOD CULTURE ( MYCO/F LYTIC BOTTLE),NaN,None,NaN,NaN,None,None,None,NaN,None
91,92,21,111970,2135-02-02,2135-02-02 05:45:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
92,93,21,111970,2135-02-02,2135-02-02 11:54:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
93,94,21,111970,2135-02-02,2135-02-02 12:15:00,70011,BLOOD CULTURE ( MYCO/F LYTIC BOTTLE),NaN,None,NaN,NaN,None,None,None,NaN,None
94,95,21,111970,2135-02-04,2135-02-04 04:08:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
95,96,22,165315,2196-04-09,2196-04-09 10:10:00,70079,URINE,NaN,None,NaN,NaN,None,None,None,NaN,None
96,97,23,152223,2153-09-04,2153-09-04 12:54:00,70064,STOOL,NaN,None,NaN,NaN,None,None,None,NaN,None
97,98,23,124321,2157-10-24,2157-10-24 12:54:00,70062,SPUTUM,NaN,None,NaN,NaN,None,None,None,NaN,None
98,99,25,129635,2160-11-02,2160-11-02 08:46:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None
99,100,25,129635,2160-11-02,2160-11-02 08:51:00,70012,BLOOD CULTURE,NaN,None,NaN,NaN,None,None,None,NaN,None